training_set_path: "/home/hli31/S2024_MLSYS/Trace/fbgemm_t856_bs65536_0_trace_801_854.pt"
# testing_set_path: "/home/hli31/S2024_MLSYS/Trace/fbgemm_t856_bs65536_0_trace_600_602.pt"
testing_set_path: "/home/hli31/S2024_MLSYS/Trace/fbgemm_t856_bs65536_0_trace_811_825.pt"

model_configs:
  hidden_dim: 512
  n_heads: 8
  n_layers: 5
  embed_dim: 128
  block_size: 2048

training_configs:
  learning_rate: 0.001
  batch_size: 64
  epochs: 50
  input_window_size: 2000
  prediction_ratio: 0.1
